import React from "react";
import Navbar from "./navbar";
import Footer from "./footer";
import Head from "next/head";
export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Joseph Anselm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  );
}
